name: CD - Publish to GitHub Packages

on:
  push:
    branches: [main]
    tags:
      - 'v*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  packages: write

jobs:
  publish-ghp:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dendelion'

      - name: Update package name for GitHub Packages
        run: |
          # GitHub Packages requires the scope to match the repo owner
          jq '.name = "@croco-dendy/mojo-ui"' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to GitHub Packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
